### ISSUE TITLE
生成词云图问题

### ISSUE THREAD

**Issue by CherryFeng** [Pinned/ICanIBBData#2]
请问在生成词云图时，str(data['content'])会把"Name：，Length：，dtype："这行也进行结巴分词，最后生成的词云图会含有Name,dtype,Length，请问这个问题是怎么解决的呢？是在停词里加入Name、Length和dtype吗？

**Comment by Pinned** [comment]
str(data["content"]) 返回的只有 content 中的具体内容啊？你是如何出现这个问题的？

**Comment by CherryFeng** [comment]
我按照您的代码写的，代码是一样的，但是词云图里出现了Name,dtype这些词。data["content"]得到的结果会有dtype、Name这些，使用str()好像就直接把最后一行的Name等也包括进去了…

**Comment by Pinned** [comment]
贴一下错误信息吧
